package
{
    import mx.messaging.channels.AMFChannel;
    import mx.effects.EffectManager;
    import mx.core.mx_internal;
    import flash.net.getClassByAlias;
    import flash.net.registerClassAlias;
    import Communication.VO.*;
    import Communication.VO.Achievements.*;
    import Communication.VO.avatarSelection.*;
    import Communication.VO.collectibles.*;
    import Communication.VO.ContentGenerator.*;
    import Communication.VO.epicWorkyard.*;
    import Communication.VO.Fulfilments.*;
    import Communication.VO.Guild.*;
    import Communication.VO.Mail.*;
    import Communication.VO.Skill.*;
    import Communication.VO.Tasks.*;
    import Communication.VO.TradeWindow.*;
    import Communication.VO.UpdateVO.*;
    import Communication.VO.Votes.*;
    import Events.dEventTimeVO;
    import Modifier.ModifierListVO;
    import Modifier.ModifierVO;
    import ServerOnly.DirtyIndicator;
    import ServerState.cTradeObject;
    import ServerState.dResource;
    import ServerState.dResourceCreationDefinition;
    import ShopSystem.PromotionVO;
    import Utils.HashMapWrapper;
    import Utils.HashSetWrapper;
    import mx.collections.ArrayCollection;
    import mx.collections.ArrayList;
    import mx.messaging.config.ConfigMap;
    import mx.messaging.messages.*;
    import mx.utils.ObjectProxy;
    import mx.styles.StyleManager;
    import mx.core.IFlexModuleFactory;
    import flash.utils.*;
    import flash.system.*;
    import mx.styles.CSSStyleDeclaration;
    import mx.styles.StyleManager;

    public class _SWMMO_FlexInit 
    {

        private static var mx_messaging_channels_AMFChannel_ref:AMFChannel;


        public static function init(fbs:IFlexModuleFactory):void
        {
            var _bootstrap:CSSStyleDeclaration = StyleManager.getStyleDeclaration("global");
            if (!_bootstrap)
            {
                _bootstrap = new CSSStyleDeclaration();
                StyleManager.setStyleDeclaration("global", _bootstrap, false);
            };
            _bootstrap.setStyle("fontAntiAliasType", "advanced");
            _bootstrap.setStyle("fontGridFitType", "pixel");
            _bootstrap.setStyle("fontSharpness", 0);
            _bootstrap.setStyle("fontThickness", 0);
            StyleManager.mx_internal::initProtoChainRoots();
            EffectManager.mx_internal::registerEffectTrigger("addedEffect", "added");
            EffectManager.mx_internal::registerEffectTrigger("completeEffect", "complete");
            EffectManager.mx_internal::registerEffectTrigger("creationCompleteEffect", "creationComplete");
            EffectManager.mx_internal::registerEffectTrigger("focusInEffect", "focusIn");
            EffectManager.mx_internal::registerEffectTrigger("focusOutEffect", "focusOut");
            EffectManager.mx_internal::registerEffectTrigger("hideEffect", "hide");
            EffectManager.mx_internal::registerEffectTrigger("itemsChangeEffect", "itemsChange");
            EffectManager.mx_internal::registerEffectTrigger("mouseDownEffect", "mouseDown");
            EffectManager.mx_internal::registerEffectTrigger("mouseUpEffect", "mouseUp");
            EffectManager.mx_internal::registerEffectTrigger("moveEffect", "move");
            EffectManager.mx_internal::registerEffectTrigger("removedEffect", "removed");
            EffectManager.mx_internal::registerEffectTrigger("resizeEffect", "resize");
            EffectManager.mx_internal::registerEffectTrigger("resizeEndEffect", "resizeEnd");
            EffectManager.mx_internal::registerEffectTrigger("resizeStartEffect", "resizeStart");
            EffectManager.mx_internal::registerEffectTrigger("rollOutEffect", "rollOut");
            EffectManager.mx_internal::registerEffectTrigger("rollOverEffect", "rollOver");
            EffectManager.mx_internal::registerEffectTrigger("showEffect", "show");
            var aliases:Array = [
                ["defaultGame.Communication.VO.Achievements.UserAchievementCategoryVO", UserAchievementCategoryVO],
                ["defaultGame.Communication.VO.Achievements.UserAchievementDataVO", UserAchievementDataVO],
                ["defaultGame.Communication.VO.Achievements.UserAchievementFinishedUpdateVO", UserAchievementFinishedUpdateVO],
                ["defaultGame.Communication.VO.Achievements.UserAchievementTriggerFinishedUpdateVO", UserAchievementTriggerFinishedUpdateVO],
                ["defaultGame.Communication.VO.Achievements.UserAchievementTriggerValueUpdateVO", UserAchievementTriggerValueUpdateVO],
                ["defaultGame.Communication.VO.Achievements.UserAchievementVO", UserAchievementVO],
                ["defaultGame.Communication.VO.AdventureTargetsVO", AdventureTargetListVO],
                ["defaultGame.Communication.VO.AdventureTargetVO", AdventureTargetVO],
                ["defaultGame.Communication.VO.ChangeNameVO", ChangeNameVO],
                ["defaultGame.Communication.VO.CollectionPartVO", CollectionPartVO],
                ["defaultGame.Communication.VO.ColoniesListVO", ColoniesListVO],
                ["defaultGame.Communication.VO.ColonyCommandVO", ColonyCommandVO],
                ["defaultGame.Communication.VO.ColonyVO", ColonyVO],
                ["defaultGame.Communication.VO.CombatCommandVO", CombatCommandVO],
                ["defaultGame.Communication.VO.CombatKillStatsVO", CombatKillStatsVO],
                ["defaultGame.Communication.VO.CombatPreviewPathVO", CombatPreviewPathVO],
                ["defaultGame.Communication.VO.CombatSlotVO", CombatSlotVO],
                ["defaultGame.Communication.VO.CombatUnitSwitchVO", CombatUnitSwitchVO],
                ["defaultGame.Communication.VO.CombatVO", CombatVO],
                ["defaultGame.Communication.VO.ConditionCollectionVO", ConditionCollectionVO],
                ["defaultGame.Communication.VO.ConditionFinishedVO", ConditionFinishedVO],
                ["defaultGame.Communication.VO.ConditionUpdatedVO", ConditionUpdatedVO],
                ["defaultGame.Communication.VO.ConditionVO", ConditionVO],
                ["defaultGame.Communication.VO.ContentGenerator.ContentGeneratorCategoryVO", ContentGeneratorCategoryVO],
                ["defaultGame.Communication.VO.ContentGenerator.ContentGeneratorContentVO", ContentGeneratorContentVO],
                ["defaultGame.Communication.VO.CooldownVO", CooldownVO],
                ["defaultGame.Communication.VO.DConsoleTextVO", DConsoleTextVO],
                ["defaultGame.Communication.VO.DestructBuildingResultVO", DestructBuildingResultVO],
                ["defaultGame.Communication.VO.EffectListVO", EffectListVO],
                ["defaultGame.Communication.VO.EffectVO", EffectVO],
                ["defaultGame.Communication.VO.EventDonationPhaseVO", EventDonationPhaseVO],
                ["defaultGame.Communication.VO.ExpeditionDifficultyDataVO", ExpeditionDifficultyDataVO],
                ["defaultGame.Communication.VO.ExpeditionDifficultyVO", ExpeditionDifficultyVO],
                ["defaultGame.Communication.VO.ExpeditionMapLevelGroupCostVO", ExpeditionMapLevelGroupCostVO],
                ["defaultGame.Communication.VO.ExpeditionMapLevelGroupDataVO", ExpeditionMapLevelGroupDataVO],
                ["defaultGame.Communication.VO.ExpeditionMapLevelGroupResourceRewardVO", ExpeditionMapLevelGroupResourceRewardVO],
                ["defaultGame.Communication.VO.ExpeditionMapLevelGroupVO", ExpeditionMapLevelGroupVO],
                ["defaultGame.Communication.VO.ExpeditionMapSizeDataVO", ExpeditionMapSizeDataVO],
                ["defaultGame.Communication.VO.ExpeditionMapSizeVO", ExpeditionMapSizeVO],
                ["defaultGame.Communication.VO.Fulfilments.CategoryVO", CategoryVO],
                ["defaultGame.Communication.VO.Fulfilment.FulfilmentFinishedUpdateVO", FulfilmentFinishedUpdateVO],
                ["defaultGame.Communication.VO.Fulfilments.FulfilmentTriggerFinishedUpdateVO", FulfilmentTriggerFinishedUpdateVO],
                ["defaultGame.Communication.VO.Fulfilments.FulfilmentTriggerValueUpdateVO", FulfilmentTriggerValueUpdateVO],
                ["defaultGame.Communication.VO.Fulfilments.IdentityVO", IdentityVO],
                ["defaultGame.Communication.VO.GameEventVO", GameEventVO],
                ["defaultGame.Communication.VO.GenericValueVO", GenericValueVO],
                ["defaultGame.Communication.VO.Guild.dGuildBankBuyTabVO", dGuildBankBuyTabVO],
                ["defaultGame.Communication.VO.Guild.dGuildBankEnlargeVO", dGuildBankEnlargeVO],
                ["defaultGame.Communication.VO.Guild.dGuildBankTabRenameVO", dGuildBankTabRenameVO],
                ["defaultGame.Communication.VO.Guild.dGuildBankTabVO", dGuildBankTabVO],
                ["defaultGame.Communication.VO.Guild.dGuildBankTransactionVO", dGuildBankTransactionVO],
                ["defaultGame.Communication.VO.Guild.dGuildBankTransferVO", dGuildBankTransferVO],
                ["defaultGame.Communication.VO.Guild.dGuildBankVO", dGuildBankVO],
                ["defaultGame.Communication.VO.Guild.dGuildBankWithdrawVO", dGuildBankWithdrawVO],
                ["defaultGame.Communication.VO.Guild.dGuildEditValueVO", dGuildEditValueVO],
                ["defaultGame.Communication.VO.Guild.dGuildHeadersListVO", dGuildHeadersListVO],
                ["defaultGame.Communication.VO.Guild.dGuildLogListItemVO", dGuildLogListItemVO],
                ["defaultGame.Communication.VO.Guild.dGuildPlayerAdventureVO", dGuildPlayerAdventureVO],
                ["defaultGame.Communication.VO.Guild.dGuildPlayerListItemVO", dGuildPlayerListItemVO],
                ["defaultGame.Communication.VO.Guild.dGuildPlayerPermissionVO", dGuildPlayerPermissionVO],
                ["defaultGame.Communication.VO.Guild.dGuildQuestVO", dGuildQuestVO],
                ["defaultGame.Communication.VO.Guild.dGuildRankListItemVO", dGuildRankListItemVO],
                ["defaultGame.Communication.VO.Guild.dGuildRankTabPermissionVO", dGuildRankTabPermissionVO],
                ["defaultGame.Communication.VO.Guild.dGuildUpdateVO", dGuildUpdateVO],
                ["defaultGame.Communication.VO.Guild.dGuildVO", dGuildVO],
                ["defaultGame.Communication.VO.HandShakeVO", HandShakeVO],
                ["defaultGame.Communication.VO.InputVO", InputVO],
                ["defaultGame.Communication.VO.IntegerListVO", IntegerListVO],
                ["defaultGame.Communication.VO.Mail.dBattleReportBodyVO", dBattleReportBodyVO],
                ["defaultGame.Communication.VO.Mail.dBuffedDataVO", dBuffedDataVO],
                ["defaultGame.Communication.VO.Mail.dDeleteMailsRequestVO", dDeleteMailsRequestVO],
                ["defaultGame.Communication.VO.Mail.dDismissMailsRequestVO", dDismissMailsRequestVO],
                ["defaultGame.Communication.VO.Mail.dFriendBodyVO", dFriendBodyVO],
                ["defaultGame.Communication.VO.Mail.dGuildBodyVO", dGuildBodyVO],
                ["defaultGame.Communication.VO.Mail.dHardCurrencyMailBodyVO", dHardCurrencyMailBodyVO],
                ["defaultGame.Communication.VO.Mail.dMailHeaderResponseVO", dMailHeaderResponseVO],
                ["defaultGame.Communication.VO.Mail.dMailVO", dMailVO],
                ["defaultGame.Communication.VO.Mail.dMarkMailsVO", dMarkMailsVO],
                ["defaultGame.Communication.VO.Mail.dNewMailCountVO", dNewMailCountVO],
                ["defaultGame.Communication.VO.PlayerOptionVO", PlayerOptionVO],
                ["defaultGame.Communication.VO.PlayerOptionsVO", PlayerOptionsVO],
                ["defaultGame.Communication.VO.PropagatingBuffListVO", PropagatingBuffListVO],
                ["defaultGame.Communication.VO.PropagatingBuffVO", PropagatingBuffVO],
                ["defaultGame.Communication.VO.PvPCommandVO", PvPCommandVO],
                ["defaultGame.Communication.VO.ReactionListVO", ReactionListVO],
                ["defaultGame.Communication.VO.ReactionVO", ReactionVO],
                ["defaultGame.Communication.VO.SetBuildingVO", SetBuildingVO],
                ["defaultGame.Communication.VO.Skill.ChangeSkillsVO", ChangeSkillsVO],
                ["defaultGame.Communication.VO.Skill.ResetSkillsVO", ResetSkillsVO],
                ["defaultGame.Communication.VO.Skill.SkillVO", SkillVO],
                ["defaultGame.Communication.VO.TaskIDVO", TaskIDVO],
                ["defaultGame.Communication.VO.Tasks.TaskClaimVO", TaskClaimVO],
                ["defaultGame.Communication.VO.Tasks.TaskDataVO", TaskDataVO],
                ["defaultGame.Communication.VO.TradeWindow.dTradeObjectVO", dTradeObjectVO],
                ["defaultGame.Communication.VO.TradeWindow.dTradeWindowResultVO", dTradeWindowResultVO],
                ["defaultGame.Communication.VO.TriggerListVO", TriggerListVO],
                ["defaultGame.Communication.VO.TriggerVO", TriggerVO],
                ["defaultGame.Communication.VO.UpdateVO.BuffAmountDiffVO", BuffAmountDiffVO],
                ["defaultGame.Communication.VO.UpdateVO.CooldownListVO", CooldownListVO],
                ["defaultGame.Communication.VO.UpdateVO.GenericValueListVO", GenericValueListVO],
                ["defaultGame.Communication.VO.UpdateVO.MapItemUpdateVO", MapItemUpdateVO],
                ["defaultGame.Communication.VO.UpdateVO.dAdventureClientInfoVO", dAdventureClientInfoVO],
                ["defaultGame.Communication.VO.UpdateVO.dAdventureExpiredVO", dAdventureExpiredVO],
                ["defaultGame.Communication.VO.UpdateVO.dAdventurePlayerVO", dAdventurePlayerVO],
                ["defaultGame.Communication.VO.UpdateVO.dAdventureResetVO", dAdventureResetVO],
                ["defaultGame.Communication.VO.UpdateVO.dAlertMessageVO", dAlertMessageVO],
                ["defaultGame.Communication.VO.UpdateVO.dBattleResultVO", dBattleResultVO],
                ["defaultGame.Communication.VO.UpdateVO.dCasualty", dCasualty],
                ["defaultGame.Communication.VO.UpdateVO.dEnabledResourceDonationsVO", dEnabledResourceDonationsVO],
                ["defaultGame.Communication.VO.UpdateVO.dExploreSectorResponseVO", dExploreSectorResponseVO],
                ["defaultGame.Communication.VO.UpdateVO.dExploredSectorVO", dExploredSectorVO],
                ["defaultGame.Communication.VO.UpdateVO.dFindEventZoneResponseVO", dFindEventZoneResponseVO],
                ["defaultGame.Communication.VO.UpdateVO.dFindExpeditionResponseVO", dFindExpeditionResponseVO],
                ["defaultGame.Communication.VO.UpdateVO.dFindTreasureResponseVO", dFindTreasureResponseVO],
                ["defaultGame.Communication.VO.UpdateVO.dFoundDepositVO", dFoundDepositVO],
                ["defaultGame.Communication.VO.UpdateVO.dHardCurrencyPurchased", dHardCurrencyPurchased],
                ["defaultGame.Communication.VO.UpdateVO.dKillSwitchUpdateVO", dKillSwitchUpdateVO],
                ["defaultGame.Communication.VO.UpdateVO.dLootItemsVO", dLootItemsVO],
                ["defaultGame.Communication.VO.UpdateVO.dMailsDismissedVO", dMailsDismissedVO],
                ["defaultGame.Communication.VO.UpdateVO.dPickupListVO", dPickupListVO],
                ["defaultGame.Communication.VO.UpdateVO.dQuestUpdateVO", dQuestUpdateVO],
                ["defaultGame.Communication.VO.UpdateVO.dRemovedAdventureVO", dRemovedAdventureVO],
                ["defaultGame.Communication.VO.UpdateVO.dRemovedFriendVO", dRemovedFriendVO],
                ["defaultGame.Communication.VO.UpdateVO.dServerSettingVO", dServerSettingVO],
                ["defaultGame.Communication.VO.UpdateVO.dTravellingSpecialistArivalVO", dTravellingSpecialistArivalVO],
                ["defaultGame.Communication.VO.Votes.dPlayerVoteItemVO", dPlayerVoteItemVO],
                ["defaultGame.Communication.VO.Votes.dPlayerVoteVO", dPlayerVoteVO],
                ["defaultGame.Communication.VO.Votes.dVoteHistoryListVO", dVoteHistoryListVO],
                ["defaultGame.Communication.VO.Votes.dVoteResultVO", dVoteResultVO],
                ["defaultGame.Communication.VO.avatarSelection.CheckUsernameVO", CheckUsernameVO],
                ["defaultGame.Communication.VO.avatarSelection.UpdateUsernameAndAvatarVO", UpdateUsernameAndAvatarVO],
                ["defaultGame.Communication.VO.collectibles.CreateCollectionRequestVO", CreateCollectionRequestVO],
                ["defaultGame.Communication.VO.collectibles.CreateCollectionResultVO", CreateCollectionResultVO],
                ["defaultGame.Communication.VO.collectibles.PickupsDataVO", PickupsDataVO],
                ["defaultGame.Communication.VO.dAcceptTradeVO", dAcceptTradeVO],
                ["defaultGame.Communication.VO.dAdventCalendarDoorVO", dAdventCalendarDoorVO],
                ["defaultGame.Communication.VO.dAdventurePlayerListItemVO", dAdventurePlayerListItemVO],
                ["defaultGame.Communication.VO.dAdventureStateChangeVO", dAdventureStateChangeVO],
                ["defaultGame.Communication.VO.dAdventureVO", dAdventureVO],
                ["defaultGame.Communication.VO.dArmyVO", dArmyVO],
                ["defaultGame.Communication.VO.dBackgroundTileVO", dBackgroundTileVO],
                ["defaultGame.Communication.VO.dBankDonationVO", dBankDonationVO],
                ["defaultGame.Communication.VO.dBaseVO", dBaseVO],
                ["defaultGame.Communication.VO.dBattleBuffTarget", dBattleBuffTarget],
                ["defaultGame.Communication.VO.dBuffApplianceVO", dBuffApplianceVO],
                ["defaultGame.Communication.VO.dBuffListVO", dBuffListVO],
                ["defaultGame.Communication.VO.dBuffVO", dBuffVO],
                ["defaultGame.Communication.VO.dBuildQueueVO", dBuildQueueVO],
                ["defaultGame.Communication.VO.dBuildingLayerVO", dBuildingLayerVO],
                ["defaultGame.Communication.VO.dBuildingVO", dBuildingVO],
                ["defaultGame.Communication.VO.dBuyOneClickShopItemVO", dBuyOneClickShopItemVO],
                ["defaultGame.Communication.VO.dBuyShopItemVO", dBuyShopItemVO],
                ["defaultGame.Communication.VO.dClientDateVO", dClientDateVO],
                ["defaultGame.Communication.VO.dClientInitDataVO", dClientInitDataVO],
                ["defaultGame.Communication.VO.dClientLogMessagesVO", dClientLogMessagesVO],
                ["defaultGame.Communication.VO.dClientTrackVO", dClientTrackVO],
                ["defaultGame.Communication.VO.dZoneLoginVO", dZoneLoginVO],
                ["defaultGame.Communication.VO.dCombatPreviewResult", dCombatPreviewResult],
                ["defaultGame.Communication.VO.dContentGeneratorRollVO", dContentGeneratorRollVO],
                ["defaultGame.Communication.VO.dDataIntStringVO", dDataIntStringVO],
                ["defaultGame.Communication.VO.dDataTrackingVO", dDataTrackingVO],
                ["defaultGame.Communication.VO.dDepositGroupVO", dDepositGroupVO],
                ["defaultGame.Communication.VO.dDepositQualityVO", dDepositQualityVO],
                ["defaultGame.Communication.VO.dDepositVO", dDepositVO],
                ["defaultGame.Communication.VO.dFilterVO", dFilterVO],
                ["defaultGame.Communication.VO.dFreeLandscapeVO", dFreeLandscapeVO],
                ["defaultGame.Communication.VO.dGameTickCommandVO", dGameTickCommandVO],
                ["defaultGame.Communication.VO.dGetFriendsVO", dGetFriendsVO],
                ["defaultGame.Communication.VO.dHelpDefinitionVO", dHelpDefinitionVO],
                ["defaultGame.Communication.VO.dIntegerVO", dIntegerVO],
                ["defaultGame.Communication.VO.dLandingFieldVO", dLandingFieldVO],
                ["defaultGame.Communication.VO.dLandscapeVO", dLandscapeVO],
                ["defaultGame.Communication.VO.dLeaveAdventureVO", dLeaveAdventureVO],
                ["defaultGame.Communication.VO.dMapValueItemVO", dMapValueItemVO],
                ["defaultGame.Communication.VO.dMoveBuildingVO", dMoveBuildingVO],
                ["defaultGame.Communication.VO.dNumberVO", dNumberVO],
                ["defaultGame.Communication.VO.dPathVO", dPathVO],
                ["defaultGame.Communication.VO.dPersistedBuffApplianceVO", dPersistedBuffApplianceVO],
                ["defaultGame.Communication.VO.dPersistedItemRegistryVO", dPersistedItemRegistryVO],
                ["defaultGame.Communication.VO.dPersistedPickupItemVO", dPersistedPickupItemVO],
                ["defaultGame.Communication.VO.dPersistedZoneSpecialistActivityVO", dPersistedZoneSpecialistActivityVO],
                ["defaultGame.Communication.VO.dPickupItemVO", dPickupItemVO],
                ["defaultGame.Communication.VO.dPlayerListItemVO", dPlayerListItemVO],
                ["defaultGame.Communication.VO.dPlayerVO", dPlayerVO],
                ["defaultGame.Communication.VO.dPlayerVotePoolVO", dPlayerVotePoolVO],
                ["defaultGame.Communication.VO.dPosVO", dPosVO],
                ["defaultGame.Communication.VO.dPurchasedShopItemVO", dPurchasedShopItemVO],
                ["defaultGame.Communication.VO.dQuestDefinitionContainerVO", dQuestDefinitionContainerVO],
                ["defaultGame.Communication.VO.dQuestDefinitionHintVO", dQuestDefinitionHintVO],
                ["defaultGame.Communication.VO.dQuestDefinitionPostrequisitsVO", dQuestDefinitionPostrequisitsVO],
                ["defaultGame.Communication.VO.dQuestDefinitionRewardVO", dQuestDefinitionRewardVO],
                ["defaultGame.Communication.VO.dQuestDefinitionTriggerVO", dQuestDefinitionTriggerVO],
                ["defaultGame.Communication.VO.dQuestDefinitionVO", dQuestDefinitionVO],
                ["defaultGame.Communication.VO.dQuestElementVO", dQuestElementVO],
                ["defaultGame.Communication.VO.dQuestPoolVO", dQuestPoolVO],
                ["defaultGame.Communication.VO.dQuestTriggerVO", dQuestTriggerVO],
                ["defaultGame.Communication.VO.dQuestVO", dQuestVO],
                ["defaultGame.Communication.VO.dRaiseArmyVO", dRaiseArmyVO],
                ["defaultGame.Communication.VO.dRequirementListsVO", dRequirementListsVO],
                ["defaultGame.Communication.VO.dRequirementVO", dRequirementVO],
                ["defaultGame.Communication.VO.dRequirementsVO", dRequirementsVO],
                ["defaultGame.Communication.VO.dResourceCreationVO", dResourceCreationVO],
                ["defaultGame.Communication.VO.dResourceVO", dResourceVO],
                ["defaultGame.Communication.VO.dResourcesVO", dResourcesVO],
                ["defaultGame.Communication.VO.dSectorDiscoveryVO", dSectorDiscoveryVO],
                ["defaultGame.Communication.VO.dSectorVO", dSectorVO],
                ["defaultGame.Communication.VO.dServerAction", dServerAction],
                ["defaultGame.Communication.VO.dServerActionResult", dServerActionResult],
                ["defaultGame.Communication.VO.dServerCall", dServerCall],
                ["defaultGame.Communication.VO.dServerClientUpdateVO", dServerClientUpdateVO],
                ["defaultGame.Communication.VO.dServerResponse", dServerResponse],
                ["defaultGame.Communication.VO.dSettingsVO", dSettingsVO],
                ["defaultGame.Communication.VO.dShowErrorVO", dShowErrorVO],
                ["defaultGame.Communication.VO.dSpecialCombatPreviewVO", dSpecialCombatPreviewVO],
                ["defaultGame.Communication.VO.dSpecialistResultVO", dSpecialistResultVO],
                ["defaultGame.Communication.VO.dSpecialistTaskVO", dSpecialistTaskVO],
                ["defaultGame.Communication.VO.dSpecialistTask_AttackBuildingNewCombatVO", dSpecialistTask_AttackBuildingNewCombatVO],
                ["defaultGame.Communication.VO.dSpecialistTask_AttackBuildingVO", dSpecialistTask_AttackBuildingVO],
                ["defaultGame.Communication.VO.dSpecialistTask_ExpeditionRecoverVO", dSpecialistTask_ExpeditionRecoverVO],
                ["defaultGame.Communication.VO.dSpecialistTask_ExploreSectorVO", dSpecialistTask_ExploreSectorVO],
                ["defaultGame.Communication.VO.dSpecialistTask_FindDepositVO", dSpecialistTask_FindDepositVO],
                ["defaultGame.Communication.VO.dSpecialistTask_FindEventZoneVO", dSpecialistTask_FindEventZoneVO],
                ["defaultGame.Communication.VO.dSpecialistTask_FindExpeditionVO", dSpecialistTask_FindExpeditionVO],
                ["defaultGame.Communication.VO.dSpecialistTask_FindTreasureVO", dSpecialistTask_FindTreasureVO],
                ["defaultGame.Communication.VO.dSpecialistTask_MoveVO", dSpecialistTask_MoveVO],
                ["defaultGame.Communication.VO.dSpecialistTask_RecoverVO", dSpecialistTask_RecoverVO],
                ["defaultGame.Communication.VO.dSpecialistTask_TravelToStarMenuVO", dSpecialistTask_TravelToStarMenuVO],
                ["defaultGame.Communication.VO.dSpecialistTask_TravelToZoneVO", dSpecialistTask_TravelToZoneVO],
                ["defaultGame.Communication.VO.dSpecialistTask_WaitForConfirmationVO", dSpecialistTask_WaitForConfirmationVO],
                ["defaultGame.Communication.VO.dSpecialistVO", dSpecialistVO],
                ["defaultGame.Communication.VO.dSquadVO", dSquadVO],
                ["defaultGame.Communication.VO.dStartSpecialistTaskVO", dStartSpecialistTaskVO],
                ["defaultGame.Communication.VO.dStreetVO", dStreetVO],
                ["defaultGame.Communication.VO.dSupportLockZone", dSupportLockZone],
                ["defaultGame.Communication.VO.dTempBuildSlotVO", dTempBuildSlotVO],
                ["defaultGame.Communication.VO.dTimedProductionQueueChangeVO", dTimedProductionQueueChangeVO],
                ["defaultGame.Communication.VO.dTimedProductionVO", dTimedProductionVO],
                ["defaultGame.Communication.VO.dTrackedMissionListVO", dTrackedMissionListVO],
                ["defaultGame.Communication.VO.dTrackedMissionVO", dTrackedMissionVO],
                ["defaultGame.Communication.VO.dTradeCompleteUpdateVO", dTradeCompleteUpdateVO],
                ["defaultGame.Communication.VO.dTradeCompleteVO", dTradeCompleteVO],
                ["defaultGame.Communication.VO.dTradeOfferVO", dTradeOfferVO],
                ["defaultGame.Communication.VO.dUniqueID", dUniqueID],
                ["defaultGame.Communication.VO.dUpdateVO", dUpdateVO],
                ["defaultGame.Communication.VO.dZoneCheckVO", dZoneCheckVO],
                ["defaultGame.Communication.VO.dZoneRefreshVO", dZoneRefreshVO],
                ["defaultGame.Communication.VO.dZoneVO", dZoneVO],
                ["defaultGame.Communication.VO.epicWorkyard.ChainVO", ChainVO],
                ["defaultGame.Communication.VO.epicWorkyard.EpicWorkyardChangeProductionVO", EpicWorkyardChangeProductionVO],
                ["defaultGame.Communication.VO.epicWorkyard.EpicWorkyardCreateProductionChainVO", EpicWorkyardCreateProductionChainVO],
                ["defaultGame.Communication.VO.epicWorkyard.EpicWorkyardStopProductionChainVO", EpicWorkyardStopProductionChainVO],
                ["defaultGame.Communication.VO.epicWorkyard.PositionVO", PositionVO],
                ["defaultGame.Events.dEventTimeVO", dEventTimeVO],
                ["defaultGame.Manipulator.ModifierListVO", ModifierListVO],
                ["defaultGame.Manipulator.ModifierVO", ModifierVO],
                ["defaultGame.ServerOnly.DirtyIndicator", DirtyIndicator],
                ["defaultGame.ServerState.cTradeObject", cTradeObject],
                ["defaultGame.ServerState.dResource", dResource],
                ["ServerState.dResourceDefinition", dResourceCreationDefinition],
                ["defaultGame.ShopSystem.PromotionVO", PromotionVO],
                ["defaultGame.Utils.HashMapWrapper", HashMapWrapper],
                ["defaultGame.Utils.HashSetWrapper", HashSetWrapper],
                ["flex.messaging.io.ArrayCollection", ArrayCollection],
                ["flex.messaging.io.ArrayList", ArrayList],
                ["flex.messaging.config.ConfigMap", ConfigMap],
                ["flex.messaging.messages.AcknowledgeMessage", AcknowledgeMessage],
                ["DSK", AcknowledgeMessageExt],
                ["flex.messaging.messages.AsyncMessage", AsyncMessage],
                ["DSA", AsyncMessageExt],
                ["flex.messaging.messages.CommandMessage", CommandMessage],
                ["DSC", CommandMessageExt],
                ["flex.messaging.messages.ErrorMessage", ErrorMessage],
                ["flex.messaging.messages.MessagePerformanceInfo", MessagePerformanceInfo],
                ["flex.messaging.messages.RemotingMessage", RemotingMessage],
                ["flex.messaging.io.ObjectProxy", ObjectProxy]
            ];
            for each (var pair:Array in aliases)
            {
                registerClassAlias(String(pair[0]), Class(pair[1]));
            }
            var styleNames:Array = ["fontAntiAliasType", "errorColor", "horizontalGridLineColor", "kerning", "backgroundDisabledColor", "iconColor", "modalTransparencyColor", "textRollOverColor", "textIndent", "verticalGridLineColor", "themeColor", "modalTransparency", "textDecoration", "headerColors", "textAlign", "fontThickness", "fontFamily", "textSelectedColor", "strokeWidth", "selectionDisabledColor", "labelWidth", "fontGridFitType", "letterSpacing", "rollOverColor", "fontStyle", "dropShadowColor", "fontSize", "shadowColor", "selectionColor", "disabledColor", "strokeColor", "dropdownBorderColor", "indicatorGap", "fontWeight", "disabledIconColor", "modalTransparencyBlur", "leading", "color", "alternatingItemColors", "fontSharpness", "barColor", "modalTransparencyDuration", "footerColors"];
            var i:int;
            while (i < styleNames.length)
            {
                StyleManager.registerInheritingStyle(styleNames[i]);
                i = (i + 1);
            }
        }


    }
}
