package 
{
    import flash.geom.Point;
    import flash.external.ExternalInterface;

    public class defines 
    {

        public static var INFO_RESOURCE_5:String = "Stone";
        public static var INFO_RESOURCE_4:String = "RealPlank";
        public static var CLIENT_FILTER:Boolean = true;
        public static var GUILD_ACTIVE:Boolean = true;
        public static var INFO_RESOURCE_6:String = "Marble";
        public static var INFO_RESOURCE_3:String = "Plank";
        public static var CLIENT_EXPERIMENTAL:int = 0;
        public static var CLIENT_ZONEID:int = 0;
        public static var CHAT_FONT_SIZE:int = 12;
        public static var INFO_RESOURCE_2:String = "Coin";
        public static var INFO_RESOURCE_1:String = "Tool";
        public static var GFX_CACHE:Boolean = false;
        public static var MAIL_DEF_ROUTE_1:int = 1;
        public static var MAIL_DEF_ROUTE_0:int = 0;
        public static var USE_EXTERNAL_SERVER:Boolean;
        public static var STATIC_FILES_URL:String;

        public static var VERSION_NR:String = "d120f9b8dd53db559ddf5d5a4dc7f6dadc7cbb77";//"9361-Release_lugia_air"
        public static const VERSION_DATE:String = "20210614-1406";
        public static const VERSION_INFO:String = "v9361-Release_lugia_air [Date: 20210614-1406]";
        public static const MIN_DB_VERSION:String = "85";
        public static const STORE_ZONE_DELTA:Boolean = true;
        public static const FILTER_ACTIVATED:Boolean = true;
        public static const DATABASE_SLOW_APPLY_CHANGE_EVENTS_THRESHOLD:Number = 2500;
        public static const GAMETICK_SYSTEM_SLOW_ZONE_THRESHOLD:Number = 5000;
        public static const GAMETICK_SYSTEM_POSTPROCESS_TIME_MIN:Number = 2500;
        public static const GAMETICK_SYSTEM_POSTPROCESS_TIME_MAX:Number = 5000;
        public static const GAMETICK_SYSTEM_POSTPROCESS_INCREASE:Number = 250;
        public static const GAMETICK_PERIODIC_REFRESH_TIME:Number = 1000;
        public static const GAMETICK_PERIODIC_ZONE_REFRESH_TOLERANCE_TIME:Number = 5000;
        public static const COOKIE_NAME:String = "TheSettlersOnline";
        public static const COOKIE_VERSION:int = 2;
        public static const GAME_STATE:String = "Game";
        public static const USE_BIG_BROTHER:Boolean = false;
        public static const BIG_BROTHER_URL:String = "http://127.0.0.1:8080/GameServer";
        public static const CHAT_SOCKET_URL:String = "http://127.0.0.1:5222/";
        public static const CHAT_BOSH_URL:String = "http://127.0.0.1:7070/";
        public static const STATIC_FILES_URL_LIST:Array = new Array();
        public static var soundEffects:Object = new Object();
        public static const DEFAULT_LANGUAGE:String = "de-de";
        public static const USER_COUNTRY:String = "de";
        public static const REALM_LANGUAGE:String = "de";
        public static const REALM_BETA_STATE:Boolean = false;
        public static const DEFAULT_UNDEFINED:String = "UNDEFINED";
        public static const COOP_ADVENTURE_CHATROOM_PREFIX:String = "*coop*";
        public static const PAYMENT_URL:String = "/redirect/shop";
        public static const FORUM_URL:String = "/redirect/forum";
        public static const SUPPORT_URL:String = "/redirect/faq";
        public static const INVITE_URL:String = "/redirect/profile";
        public static const RANKINGS_URL:String = "/redirect/rankings";
        public static const KEEP_ALIVE_URL:String = "/ping.php";
        public static const KEEP_ALIVE_INTERVAL:int = 30;
        public static const EXTENDED_BUILDING_SELECTION:Boolean = true;
        public static const FILENAME_GAME_DEBUG_SETTINGS:String = "game_settings_debug.xml";
        public static const FILENAME_GAME_SETTINGS:String = "game_settings.xml";
        public static const FILENAME_UNITS:String = "game_units.xml";
        public static const FILENAME_GFX_SETTINGS:String = "gfx_settings.xml";
        public static const FILENAME_SOUND_SETTINGS:String = "sound_settings.xml";
        public static const FILENAME_QUEST_SETTINGS:String = "quest_settings.xml";
        public static const FILENAME_SHOP_CONFIG:String = "shopconfig.xml";
        public static const FILENAME_HELP_DEFINITIONS:String = "help_definitions.xml";
        public static const FILENAME_GAME_EVENTS:String = "game_events.xml";
        public static const FILENAME_EXPEDITION_MAP_RULES:String = "game_expedition_map_rules.xml";
        public static const FILENAME_EXPEDITION_MAPS:String = "game_expedition_maps.xml";
        public static const UPDATE_REFRESH:int = 5;
        public static const UPDATE_REFRESH_MS:int = (UPDATE_REFRESH * 1000);//5000
        public static const UPDATE_REFRESH_COMMAND_MS:int = (UPDATE_REFRESH_MS + 2500);//7500
        public static const FILENAME_ITEM_LIMITS:String = "item_limits.xml";
        public static const FILENAME_COLLECTIONS_DEFINITIONS:String = "collections_definitions.xml";
        public static const FILENAME_ADVENT_CALENDAR_CONFIG:String = "advent_calendar_config_default.xml";
        public static const FILENAME_EPIC_WORKYARD:String = "epic_workyard_definitions.xml";
        public static const FILENAME_ACHIEVEMENTS_DEFINITIONS:String = "achievements_definitions.xml";
        public static const FILENAME_TASK_DEFINITIONS:String = "task_building_definitions.xml";
        public static const FILENAME_COLLECTION_GENERATOR_DEFINITIONS:String = "content_generator.xml";
        public static const FILENAME_TRIGGER_DEFINITIONS:String = "trigger_loca_definitions.xml";
        public static const FILENAME_VOTES_DEFINITIONS:String = "votes_config_default.xml";
        public static const FILENAME_VOTES_SHOP_GROUP:String = "votes_shop_group.xml";
        public static const FILENAME_EVENTS_CONFIG:String = "events_config.xml";
        public static const GENERIC_VALUES_CONFIG:String = "generic_values.xml";
        public static const REACTIONS_CONFIG:String = "reactions.xml";
        public static const MAX_FREE_LANDSCAPES:int = 500;
        public static const ACTIVATE_STREAMING:Boolean = true;
        public static const STREAMING_SET_SCREEN_TO_BLACK_UNTIL_BACKGROUND_IS_STREAMED:Boolean = true;
        public static const FADEIN_TIME:Number = 250;
        public static const INT_SCALE_FACTOR:int = 10000;
        public static const BUILDING_PROGRESS_SCALE_FACTOR:int = 10000;
        public static const MAX_DOUBLE_VALUE:Number = Number.MAX_VALUE;//1.79769313486232E308
        public static const MAX_INT_VALUE:int = 2147483647;
        public static const MAX_SPOOL_TIME:int = (((1000 * 60) * 60) * 24);//86400000
        public static const UNUSED_PLAYER_ID:int = 2147483647;
        public static const SAVEGAME_VERSION_NR_MAP_WITH_128:int = 1;
        public static const SAVEGAME_VERSION_NR:int = 2;
        public static const ANIMATE_FRAME_RATE:int = 15;
        public static const MAP_SCROLL_ACTIVATE_DELTA:Number = 1;
        public static const WAREHOUSE_FULL_WAIT_TIME:int = 50000;
        public static const POPULATION_WAIT_TIME:int = 50000;
        public static const PRODUCTION_STOP_WAITTIME:int = 2500;
        public static const BUFF_BLOCKING_DURATION:int = 8000;
        public static const BUILDING_INFO_ICON_TIME_FOR_DELAY:Number = ((60 * 1000) * 60);//3600000
        public static const MIN_UPGRADE_TIME_TO_MOVE_UPGRADING_BUILDING_FOR_GUI:int = 60000;
        public static const MIN_UPGRADE_TIME_TO_MOVE_UPGRADING_BUILDING_FOR_GAMETICK:int = 10000;
        public static const MAX_PRODUCTION_AMOUNT:int = 25;
        public static const MAX_PRODUCTION_STACKS:int = 200;
        public static const NUM_PVP_COLONY_CANDIDATES:int = 9;
        public static const MAX_NUM_COLONY_SLOTS:int = 6;
        public static const PVP_SEARCH_LEVEL_RANGE:Number = 5;
        public static const START_SECTOR:int = 7;
        public static const DEFAULT_BACKGROUND_CLEAR_COLOR:uint = 4151151;
        public static const SECTORS_X:int = 3;
        public static const SECTORS_Y:int = 3;
        public static const MAIN_ISLAND_SECTORS:int = (SECTORS_X * SECTORS_Y);//9
        public static const ISLAND_SECTORS_X:int = 1;
        public static const ISLAND_SECTORS_Y:int = 1;
        public static const ZOOM_SECTORS_ISLAND_Y:int = 3;
        public static const BORDER_OFFSET_X:int = 1600;
        public static const BORDER_OFFSET_Y:int = 800;
        public static const STREET_ZONE_BORDER:int = 2;
        public static const STREET_ZONE_SIZE_X:int = 2100;
        public static const STREET_ZONE_SIZE_Y:int = 1400;
        public static const STREET_ZONE_ISLAND_Y:int = 124;
        public static const WINDOW_SIZE_MIN_WIDTH:int = 968;
        public static const WINDOW_SIZE_MIN_HEIGHT:int = 576;
        public static const WINDOW_SIZE_FB_WIDTH:int = 760;
        public static const WINDOW_SIZE_FB_HEIGHT:int = 595;
        public static const WAREHOUSES_NAME_string:String = "Warehouse";
        public static const MAYORHOUSE_NAME_string:String = "Mayorhouse";
        public static const BARRACKS_NAME_string:String = "Barracks";
        public static const BARRACKS3_NAME_string:String = "Barracks3";
        public static const EXPEDITION_WEAPONSMITH_NAME_string:String = "ExpeditionWeaponSmith";
        public static const BOOKBINDER_NAME_string:String = "Bookbinder";
        public static const TAVERN_NAME_string:String = "Tavern";
        public static const GARRISON_NAME_string:String = "Garrison";
        public static const TRANSPORTER_GARRISON_NAME_string:String = "TransporterGarrison";
        public static const PROVISIONHOUSE_NAME_string:String = "ProvisionHouse";
        public static const LOGISTICS_NAME_string:String = "Logistics";
        public static const GUILDHOUSE_NAME_string:String = "guild_building";
        public static const GUILDBANK_NAME_string:String = "guild_bank_building";
        public static const PVPPROGRESSIONHOUSE_NAME_string:String = "pvp_progression_building";
        public static const DEPOSITFOUND_NAME_string:String = "MineFound";
        public static const DEPOSIT_HIDDEN_string:String = "DepositHidden";
        public static const EVENT_MONSTER_NAME_string:String = "EventMonster";
        public static const DEFENSE_MODE_GHOST_GARRISON_string:String = "DefenseModeGhostGarrison";
        public static const DESTROYABLE_MOUNTAIN_string:String = "DestroyableMountain";
        public static const SPECIAL_WAREHOUSES_NAME_string:String = "SpecialWarehouse";
        public static const PLAYER_RANGED_EXPEDITION_CAMP_string:String = "PlayerRangedExpeditionCamp";
        public static const PLAYER_MELEE_EXPEDITION_CAMP_string:String = "PlayerMeleeExpeditionCamp";
        public static const PLAYER_CAV_EXPEDITION_CAMP_string:String = "PlayerCavExpeditionCamp";
        public static const PLAYER_MIXED_EXPEDITION_CAMP_string:String = "PlayerMixedExpeditionCamp";
        public static const PLAYER_CAMP_TYPE_RANGED_string:String = "Ranged";
        public static const PLAYER_CAMP_TYPE_MELEE_string:String = "Melee";
        public static const PLAYER_CAMP_TYPE_CAV_string:String = "Cav";
        public static const PLAYER_CAMP_TYPE_MIXED_string:String = "Mixed";
        public static const DEFENSE_MODE_BUILDINGS_UI_string:String = "player_camp";
        public static const BUILDING_CATEGORY_GARRISON:String = "garrison";
        public static const ENEMY_BANDIT_CAMP:String = "Enemy";
        public static const BUFFED_BUILDINGS:String = "BuffedBuildings";
        public static const MINEDEPOSITDEPLETED_NAME_string:String = "MineDepleted";
        public static const ADVENTURE_BUFF:String = "Adventure";
        public static const PRODUCTIVITY_BUFF:String = "ProductivityBuff";
        public static const PRODUCTIVITY_AREA_BUFF:String = "ProductivityAreaBuff";
        public static const SPEEDUP_POPULATION_GROWTH_BUFF:String = "SpeedUpPopulationGrowth";
        public static const HALLOWEEN_EVENT_BUFF:String = "HalloweenEvent";
        public static const RECRUITING_BUFF:String = "RecruitingBuff";
        public static const FILL_DEPOSIT_BUFF:String = "FillDeposit";
        public static const ADD_RESOURCE_BUFF:String = "AddResource";
        public static const BUILD_BUILDING_BUFF:String = "BuildBuilding";
        public static const BUILD_DEFENSE_MODE_BUILDING_BUFF:String = "BuildDefenseModeBuilding";
        public static const CHANGE_COLOR_SCHEME_BUFF:String = "ChangeColorScheme";
        public static const EVENT_BUFF:String = "EventBuff";
        public static const PROVISIONER_BUFF:String = "ProvisionerBuff";
        public static const HIRED_MILITARY_BUFF:String = "HiredMilitary";
        public static const CHANGE_SKIN_BUFF:String = "ChangeSkin";
        public static const DONATE_TEMP_BUFF:String = "#donate-resource#";
        public static const WITHDRAW_TEMP_BUFF:String = "#withdraw-resource#";
        public static const TRANSFER_TEMP_BUFF:String = "#transfer-resource#";
        public static const PREMIUM_ACCOUNT_BUFF:String = "PremiumAccount";
        public static const CHANGE_AVATAR_BUFF:String = "ChangeAvatar";
        public static const BATTLE_BUFF_HURT:String = "BattleBuffHurt";
        public static const ADD_RECIPE_BUFF:String = "AddRecipe";
        public static const REMOVE_BUFF_BUFF:String = "RemoveBuff";
        public static const EMPTY_EFFECT_BUFF:String = "EmptyEffectBuff";
        public static const EFFECT_BUFF:String = "EffectBuff";
        public static const QUEST_START_BUFF:String = "QuestStart";
        public static const LOOTTABLE_BUFF:String = "Loottable";
        public static const FILL_DEPOSIT_BUFF_ID:int = 17;
        public static const ADD_RESOURCE_BUFF_ID:int = 18;
        public static const BUILD_BUILDING_BUFF_ID:int = 20;
        public static const ADVENTURE_BUFF_ID:int = 22;
        public static const HIRED_MILITARY_BUFF_ID:int = 52;
        public static const MAX_BUILDING_OFFSET:int = 20;
        public static const POPULATION_RESOURCE_NAME_string:String = "Population";
        public static const HARD_CURRENCY_RESOURCE_NAME_string:String = "HardCurrency";
        public static const WOOD_RESOURCE_NAME_string:String = "Wood";
        public static const COIN_RESOURCE_NAME_string:String = "Coin";
        public static const GUILDCOIN_RESOURCE_NAME_string:String = "GuildCoins";
        public static const MANUSCRIPT_RESOURCE_NAME_string:String = "Manuscript";
        public static const TOME_RESOURCE_NAME_string:String = "Tome";
        public static const CODEX_RESOURCE_NAME_string:String = "Codex";
        public static const XP_CONVERSION_STAR_COIN_string:String = "StarCoin";
        public static const DEFENSE_POINT_NAME_string:String = "DefensePoint";
        public static const VALOR_POINT_NAME_string:String = "ValorPoint";
        public static const STREET_DIR_NOF:int = 4;
        public static const STREET_ELEMENT_NAME_string:String = "Street_";
        public static const DIR8_NORTH_EAST:int = 0;
        public static const DIR8_SOUTH_EAST:int = 1;
        public static const DIR8_SOUTH_WEST:int = 2;
        public static const DIR8_NORTH_WEST:int = 3;
        public static const DIR8_NORTH:int = 4;
        public static const DIR8_EAST:int = 5;
        public static const DIR8_SOUTH:int = 6;
        public static const DIR8_WEST:int = 7;
        public static const DIR8_MAX:int = 8;
        public static const DIR8_NORTH_EAST_BIT:int = (1 << 0);
        public static const DIR8_SOUTH_EAST_BIT:int = (1 << 1);
        public static const DIR8_SOUTH_WEST_BIT:int = (1 << 2);
        public static const DIR8_NORTH_WEST_BIT:int = (1 << 3);
        public static const DIR8_NORTH_BIT:int = (1 << 4);
        public static const DIR8_EAST_BIT:int = (1 << 5);
        public static const DIR8_SOUTH_BIT:int = (1 << 6);
        public static const DIR8_WEST_BIT:int = (1 << 7);
        public static const DIR8_FILLED_BIT:int = (1 << 8);
        public static const DIR4_NORTH_EAST:int = DIR8_NORTH_EAST;//0
        public static const DIR4_SOUTH_EAST:int = DIR8_SOUTH_EAST;//1
        public static const DIR4_SOUTH_WEST:int = DIR8_SOUTH_WEST;//2
        public static const DIR4_NORTH_WEST:int = DIR8_NORTH_WEST;//3
        public static const NEIGHBOUR_NORTH:int = 1;
        public static const NEIGHBOUR_NORTH_EAST:int = 2;
        public static const NEIGHBOUR_EAST:int = 4;
        public static const NEIGHBOUR_SOUTH_EAST:int = 8;
        public static const NEIGHBOUR_SOUTH:int = 16;
        public static const NEIGHBOUR_SOUTH_WEST:int = 32;
        public static const NEIGHBOUR_WEST:int = 64;
        public static const NEIGHBOUR_NORTH_WEST:int = 128;
        public static const ZERO_POINT:Point = new Point(0, 0);
        public static const SCROLL_NOT:int = 0;
        public static const SCROLL_UP:int = 1;
        public static const SCROLL_DOWN:int = 2;
        public static const SCROLL_LEFT:int = 3;
        public static const SCROLL_RIGHT:int = 4;
        public static const CLEAR_COLOR:uint = 4151151;
        public static const GUI_RIGHT_BORDER:uint = 8;
        public static const GUI_LOWER_BORDER:uint = 8;
        public static const SECTOR_TYP_UNDEFINED:int = -1;
        public static const SECTOR_TYP_OPEN:int = 0;
        public static const SECTOR_TYP_CLOSED:int = 1;
        public static const USER_DATA_STREET_BORDER_LEFT:int = 1;
        public static const USER_DATA_STREET_BORDER_RIGHT:int = 2;
        public static const USER_DATA_STREET_BORDER_UP:int = 3;
        public static const USER_DATA_STREET_BORDER_DOWN:int = 4;
        public static const SETTLER_BUILDER_string:String = "Carrier";
        public static const SETTLER_DEFAULT_WORKER_string:String = "Carrier_";
        public static const LOAD_SECTOR_MODE_START_ECONOMY:int = 0;
        public static const LOAD_SECTOR_MODE_EDITOR_MODE:int = 1;
        public static const LOAD_SECTOR_MODE_DO_NOT_SET_GAME_RELEVANT_DATA:int = 2;
        public static const ILLEGAL_INT_POS:int = -32767;
        public static const NO_PLAYERID:int = -32767;
        public static const INVALID_USER_ID:int = -1;
        public static const PVP_USER_ID:int = -2;
        public static const ADVENTUREZONEID:int = -100;
        public static const ACTIVATE_CHAT:Boolean = true;
        public static const TRADE_REFRESH_INTERVAL:int = 30;
        public static const MAX_TRADE_LIMIT:int = 400;
        public static const CHECK_PRODUCTION_VALUE_TRIGGER_INTERVAL:int = 30;
        public static const EVENT_SPEND_RESOURCE_GUILD_ID:int = -1;
        public static const GUILD_BANK_REFRESH_INTERVAL:int = 30;
        public static const GUILD_BANK_PAYTAB_SIZE:int = 100000000;
        public static const RESOURCE_DICTIONARY_BUILDINGS:String = "buildings";
        public static const RESOURCE_DICTIONARY_RESOURCES:String = "resources";
        public static const RESOURCE_DICTIONARY_MILITARY:String = "military";
        public static const RESOURCE_DICTIONARY_BUFFS:String = "buffs";
        public static const RESOURCE_DICTIONARY_SHOPITEMS:String = "shopItems";
        public static const RESOURCE_DICTIONARY_ICONSPACK:String = "iconspack";
        public static const TRANSACTION_FROM_SHOP:int = 0;
        public static const TRANSACTION_FROM_PROMOTION:int = 1;
        public static const TRANSACTION_FROM_WIDGET:int = 2;
        public static const SEARCH_PLAYERLIST_BY_NAME_MIN_CHAR_LEN:int = 3;
        public static const SEARCH_PLAYERLIST_BY_NAME_MAX_RESULTS:int = 15;
        public static const NOTIFIER_BUILDING_READY:String = "BuildingReady";
        public static const INFINITE_MANA_LIMIT:int = 200;
        public static const BATTLE_BUFF_KILL_RANDOM_FLAG:int = (1 << 1);
        public static const BATTLE_BUFF_BOMB_FLAG:int = (1 << 2);
        public static const BATTLE_BUFF_KILL_COMBATANT_FLAG:int = (1 << 3);
        public static const CURRENCY_GEMS:String = "Gems";
        public static const CURRENCY_GEMS_GEMPIT:String = "GemPit Gems";
        public static const ACHIEVEMENT_THROTTLE_MODE_ACTIVE:Boolean = false;
        public static const ACHIEVEMENT_THROTTLE_MODE_MAX_NUMBER_OF_FINISHED_ACHIEVEMENTS:int = 10;
        public static const PACKET_LOSS_MILLISECONDS_UNTIL_DISCONNECT:int = (30 * 1000);//30000
        public static var CLIENT_PACKET_LOSS_TIMEOUT:int = (30 * 1000);//30000
        public static const PACKET_LOSS_MINIMUM_UPDATE_INTERVALL_MILLISECONDS:int = 500;
        public static const DEFENSE_MODE_DISABLED:Boolean = false;
        public static const FRIEND_INVITE_ENABLED:Boolean = true;
        public static const PVP_XP_string:String = "PvPXP";
        public static const MAX_DIFFICULTY_ADVENTURE:int = 10;
        public static const MAX_DIFFICULTY_EXPEDITION:int = 3;
        public static const VOLUME_MAX_VALUE:Number = 6;
        public static const PARTNER_STEAM:String = "steam";
        public static const PARTNER_KONGREGATE:String = "kongregate";
        public static const PARTNER_STANDALONE:String = "standaloneuplay";
        public static const MAIN_GUILD_QUEST_STARTER:String = "mainGuildQuestStarter";
        public static const EFFECT_DISABLED_UID:int = -999;
        public static const EFFECT_ENABLED_UID:int = -998;
        public static const PREMIUM_DUMMY_ZONE_BUFF_ID:int = -990;
        public static const EFFECT_COMPLETED_UID:int = -997;
        public static const TASK_BUILDING_UI_NAME_string:String = "taskbuilding";
        public static const BUILDING_UI_CULTURE:String = "culture";
        public static const TRACK_WEBSHOP:String = "webshop";
        public static const TRACK_WEBSHOP_WIDGET:String = "widget";
        public static const TRACK_FACEBOOK_ACHIEVEMENT:String = "FacebookPostAchievement";
        public static const NO_LIMIT:int = -996;
        public static const EXIT_CODE_RESTART:int = -3;
        public static var CLIENT_AUTHRANDOM:int = Math.floor((Math.random() * (int.MAX_VALUE - 1)));//0

        {
            init();
        }


        private static function init():void
        {
            STATIC_FILES_URL = "http://127.0.0.1/SWMMO";
            USE_EXTERNAL_SERVER = true;
            if (!ExternalInterface.available)
            {
                STATIC_FILES_URL = "..";
            };
        }

        public static function isGarrison(_arg_1:String):Boolean
        {
            return ((!(_arg_1 == null)) && (!(_arg_1.indexOf(GARRISON_NAME_string) == -1)));
        }


    }
}
